# Generated by Django 5.1.4 on 2026-05-11 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0006_bracketslot_away_source_group_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_match', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('points_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('matchup_type', models.CharField(choices=[('exact', 'Exact score'), ('diff', 'Correct goal difference'), ('result', 'Correct outcome'), ('penalty_loser_bonus', 'Penalty loser bonus'), ('miss', 'Wrong / no points'), ('no_prediction', 'No prediction'), ('no_result', 'Actual result not entered')], default='no_prediction', max_length=24)),
                ('earning_round_order', models.PositiveSmallIntegerField(blank=True, help_text='Order of the prediction round whose prediction earned these points. Null when no points were earned (miss / no prediction / no result).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='tournament.bracketslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='scoring_slo_user_id_e2cc50_idx'), models.Index(fields=['slot'], name='scoring_slo_slot_id_d8152c_idx'), models.Index(fields=['earning_round_order'], name='scoring_slo_earning_75c292_idx')],
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
