# Generated by Django 5.1.4 on 2026-05-18 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        ('tournament', '0007_stage_pool_diff_stage_pool_exact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GanyanScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_exact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('score_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('score_result', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('score_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outcome', models.CharField(choices=[('exact', 'Exact score'), ('diff', 'Correct goal difference'), ('result', 'Correct outcome'), ('penalty_pass', 'Penalty advancer (KO only)'), ('miss', 'Wrong / no points'), ('no_prediction', 'No prediction'), ('no_result', 'Actual result not entered')], default='no_prediction', max_length=16)),
                ('wrong_count_contribution', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganyan_scores', to='tournament.predictionround')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganyan_scores', to='tournament.bracketslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganyan_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='scoring_gan_user_id_dc53ee_idx'), models.Index(fields=['slot'], name='scoring_gan_slot_id_5c0e26_idx'), models.Index(fields=['outcome'], name='scoring_gan_outcome_2b8b3c_idx')],
                'unique_together': {('user', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='MatchPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('exact', 'Exact score'), ('diff', 'Goal difference'), ('result', 'Outcome (1X2)'), ('penalty_pass', 'Penalty advancer')], max_length=16)),
                ('pool_size', models.PositiveIntegerField(help_text='Snapshot of Stage.pool_<criterion> at compute time.')),
                ('predictor_count', models.PositiveIntegerField(default=0, help_text='Total unique users who predicted this slot in any round (= N).')),
                ('winner_count', models.PositiveIntegerField(default=0, help_text='Users whose at-least-one round prediction satisfied this criterion.')),
                ('base_payout', models.DecimalField(blank=True, decimal_places=2, help_text='pool_size / winner_count, before round weight. Null when winner_count = 0 (pool burned).', max_digits=10, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Per-prediction-value counts for the ganyan tablosu UI.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournament.bracketslot')),
            ],
            options={
                'indexes': [models.Index(fields=['slot'], name='scoring_mat_slot_id_4614ec_idx')],
                'unique_together': {('slot', 'criterion')},
            },
        ),
    ]
