# Generated by Django 5.1.4 on 2026-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_ganyanscore_matchpool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganyanscore',
            name='outcome',
            field=models.CharField(choices=[('exact', 'Exact score'), ('diff', 'Correct goal difference'), ('result', 'Correct outcome'), ('penalty', 'Penalty shootout only (KO)'), ('miss', 'Wrong / no points'), ('no_prediction', 'No prediction'), ('no_result', 'Actual result not entered')], default='no_prediction', max_length=16),
        ),
        migrations.AlterField(
            model_name='matchpool',
            name='criterion',
            field=models.CharField(choices=[('exact', 'Exact score'), ('diff', 'Goal difference'), ('result', 'Outcome (1X2)'), ('penalty_winner', 'Penalty advancer'), ('penalty_score', 'Penalty shootout exact score'), ('penalty_diff', 'Penalty shootout difference')], max_length=16),
        ),
    ]
