# Generated by Django 5.1.4 on 2026-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_ganyanscore_outcome_alter_matchpool_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpool',
            name='predictor_count',
            field=models.PositiveIntegerField(default=0, help_text='Users whose effective pick is on the actual fixture (= N). Wrong-matchup picks (a different bracket) are excluded.'),
        ),
    ]
