# Generated by Django 5.1.4 on 2026-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_matchpool_predictor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpool',
            name='criterion',
            field=models.CharField(choices=[('exact', 'Exact score'), ('diff', 'Goal difference'), ('result', 'Outcome (1X2)'), ('penalty_winner', 'Penalty shootout winner (shootout predictions only)'), ('penalty_score', 'Penalty shootout exact score'), ('penalty_diff', 'Penalty shootout difference'), ('advancer', 'Advancing team (open to all, pens matches only)')], max_length=16),
        ),
    ]
