# Generated by Django 5.1.4 on 2026-05-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional — pre-fills the sign-up form for this address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='invite',
            name='note',
            field=models.CharField(blank=True, help_text='Internal note: who this invite is for.', max_length=200),
        ),
    ]
