# Generated by Django 5.1.4 on 2026-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invite_email_alter_invite_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_undeliverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_undeliverable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_undeliverable_reason',
            field=models.CharField(blank=True, choices=[('bounce', 'Bounced'), ('complaint', 'Complained')], max_length=16),
        ),
    ]
