# Generated by Django 5.1.4 on 2026-06-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0010_actualresult_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Provider match id (football-data). Blank until mapped.', max_length=32)),
                ('provider', models.CharField(default='football-data', max_length=32)),
                ('status', models.CharField(blank=True, help_text='Latest provider status (SCHEDULED, IN_PLAY, PAUSED, FINISHED, ...).', max_length=20)),
                ('minute', models.PositiveSmallIntegerField(blank=True, help_text='Live match minute, when the provider reports it.', null=True)),
                ('finalized', models.BooleanField(default=False, help_text='FINISHED has been captured. The poller skips this slot from now on.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_sync', to='tournament.bracketslot')),
            ],
            options={
                'verbose_name': 'match sync',
                'verbose_name_plural': 'match syncs',
            },
        ),
    ]
