# Generated by Django 5.1.4 on 2026-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveresults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsync',
            name='injury_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Added/stoppage minutes (provider injuryTime); shown as 90+N′.', null=True),
        ),
    ]
