# Generated by Django 5.1.4 on 2026-05-09 07:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GROUP', 'Group Stage'), ('R32', 'Round of 32'), ('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('THIRD', 'Third Place Match'), ('FINAL', 'Final')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(help_text='0 = Group, 6 = Final (defines progression)')),
                ('points_exact', models.PositiveSmallIntegerField(help_text='Points awarded when the predicted score exactly matches the actual score.')),
                ('points_diff', models.PositiveSmallIntegerField(help_text='Points for correct outcome AND correct goal difference (but wrong exact score).')),
                ('points_result', models.PositiveSmallIntegerField(help_text='Points for correct outcome only (winner or draw).')),
                ('penalty_loser_pct', models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='When a user did NOT predict a draw but correctly named the team that advanced through penalties: percentage of `points_result` they receive (rounded to nearest integer, then multiplied by round weight).', max_digits=4)),
            ],
            options={
                'ordering': ('tournament', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='3-letter code (TUR, BRA, ESP).', max_length=3)),
                ('name_tr', models.CharField(help_text='Country name in Turkish (user-facing).', max_length=100)),
                ('flag_emoji', models.CharField(blank=True, help_text='Flag emoji 🇹🇷 (fallback display until SVG flags are added).', max_length=8)),
                ('group_letter', models.CharField(blank=True, help_text="A-L for the 12 groups in 2026. Empty for teams that didn't reach group stage.", max_length=1)),
            ],
            options={
                'ordering': ('group_letter', 'name_tr'),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Only one active tournament should exist at a time (drives default UI selections).')),
                ('timezone', models.CharField(default='Europe/Istanbul', help_text='Default display TZ for anonymous visitors. Authenticated users use their own.', max_length=64)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='BracketSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, help_text="Stable ID, e.g., 'GroupA-M1', 'R32-1', 'QF-3', 'Final', 'Third'.", max_length=30)),
                ('scheduled_kickoff', models.DateTimeField(help_text="UTC; rendered in user's TZ.")),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('home_source', models.CharField(blank=True, help_text="Source description for unresolved slots, e.g., 'Group A 1st' or 'Winner of R32-1'.", max_length=80)),
                ('away_source', models.CharField(blank=True, max_length=80)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='tournament.stage')),
                ('away_team_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_slots', to='tournament.team')),
                ('home_team_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_slots', to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tournament.tournament')),
            ],
            options={
                'ordering': ('scheduled_kickoff',),
                'unique_together': {('tournament', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ActualResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField(help_text="Score at the end of regulation (90').")),
                ('away_score', models.PositiveSmallIntegerField(help_text="Score at the end of regulation (90').")),
                ('went_to_extra_time', models.BooleanField(default=False)),
                ('went_to_penalties', models.BooleanField(default=False)),
                ('home_penalties', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_penalties', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournament.bracketslot')),
                ('penalty_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_wins', to='tournament.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('tournament', 'kind')},
        ),
        migrations.CreateModel(
            name='PredictionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Pre-tournament', 'After Group Stage'.", max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('deadline', models.DateTimeField(help_text='UTC; predictions for this round can no longer be edited after this.')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Score multiplier (1.00 = full points, 0.50 = half points).', max_digits=4)),
                ('editable_stages', models.ManyToManyField(help_text='Which stages can be predicted/edited in this round.', related_name='editable_in_rounds', to='tournament.stage')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_rounds', to='tournament.tournament')),
            ],
            options={
                'ordering': ('tournament', 'order'),
                'unique_together': {('tournament', 'order')},
            },
        ),
    ]
