# Generated by Django 5.1.4 on 2026-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag_emoji',
            field=models.CharField(blank=True, help_text='Flag emoji (16 chars to fit subdivision flags like England/Scotland tag sequences).', max_length=16),
        ),
    ]
