# Generated by Django 5.1.4 on 2026-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_team_flag_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag_emoji',
            field=models.CharField(blank=True, help_text='Flag emoji (fallback when SVG fails or in plain-text contexts).', max_length=16),
        ),
    ]
