# Generated by Django 5.1.4 on 2026-05-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_team_flag_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketslot',
            name='away_source_kind',
            field=models.CharField(choices=[('WINNER', 'Winner of source slot'), ('LOSER', 'Loser of source slot')], default='WINNER', max_length=8),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='away_source_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_away_to', to='tournament.bracketslot'),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='home_source_kind',
            field=models.CharField(choices=[('WINNER', 'Winner of source slot'), ('LOSER', 'Loser of source slot')], default='WINNER', max_length=8),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='home_source_slot',
            field=models.ForeignKey(blank=True, help_text='The slot whose winner/loser feeds the home side of this slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_home_to', to='tournament.bracketslot'),
        ),
    ]
