# Generated by Django 5.1.4 on 2026-05-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_bracketslot_away_source_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionround',
            name='depends_on_stage',
            field=models.ForeignKey(blank=True, help_text='Round opens only after EVERY slot in this stage has an actual result. Pre-tournament rounds leave this null.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opens_rounds', to='tournament.stage'),
        ),
        migrations.AddField(
            model_name='predictionround',
            name='opens_at',
            field=models.DateTimeField(blank=True, help_text='UTC; round stays closed until this moment. Typically auto-set by seed to (last source-stage match kickoff + buffer for ET/penalties).', null=True),
        ),
    ]
