# Generated by Django 5.1.4 on 2026-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_predictionround_depends_on_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracketslot',
            name='away_source_group_letter',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='away_source_group_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='away_source_thirds_groups',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='home_source_group_letter',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='home_source_group_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracketslot',
            name='home_source_thirds_groups',
            field=models.CharField(blank=True, default='', help_text="Comma-separated group letters for best-third sources (e.g., 'A,B,C,D,F').", max_length=20),
        ),
    ]
