# Generated by Django 5.1.4 on 2026-05-18 12:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_bracketslot_away_source_group_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='pool_diff',
            field=models.PositiveIntegerField(default=100, help_text='Ganyan pool size for goal-difference winners.'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pool_exact',
            field=models.PositiveIntegerField(default=100, help_text='Ganyan pool size for exact-score winners. Split equally; burns if no one is correct.'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pool_penalty_pass',
            field=models.PositiveIntegerField(default=50, help_text="Ganyan pool size for the 'predicted the team that advanced via penalties' criterion. Only relevant on knockout stages."),
        ),
        migrations.AddField(
            model_name='stage',
            name='pool_result',
            field=models.PositiveIntegerField(default=100, help_text='Ganyan pool size for outcome (1X2) winners.'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='penalty_loser_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='LEGACY engine only. When a user did NOT predict a draw but correctly named the team that advanced through penalties: percentage of `points_result` they receive (rounded to nearest integer, then multiplied by round weight).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='stage',
            name='points_diff',
            field=models.PositiveSmallIntegerField(help_text='LEGACY engine only. Points for correct outcome AND correct goal difference (but wrong exact score).'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='points_exact',
            field=models.PositiveSmallIntegerField(help_text='LEGACY engine only. Points awarded when the predicted score exactly matches the actual score.'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='points_result',
            field=models.PositiveSmallIntegerField(help_text='LEGACY engine only. Points for correct outcome only (winner or draw).'),
        ),
    ]
