# Generated by Django 5.1.4 on 2026-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_stage_pool_diff_stage_pool_exact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='pool_penalty_pass',
        ),
        migrations.AddField(
            model_name='stage',
            name='pool_penalty_diff',
            field=models.PositiveIntegerField(default=50, help_text='Ganyan pool: predicted the penalty shootout goal difference (signed home−away). Draw predictions only. Knockout only.'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pool_penalty_score',
            field=models.PositiveIntegerField(default=50, help_text='Ganyan pool: predicted the exact penalty shootout score. Only draw predictions carry a shootout score, so this is open to them only. Knockout only.'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pool_penalty_winner',
            field=models.PositiveIntegerField(default=50, help_text='Ganyan pool: correctly named the team that advanced via penalties. Open to any prediction (implied winner from a non-draw, chosen penalty winner from a draw). Knockout only.'),
        ),
    ]
