# Generated by Django 5.1.4 on 2026-06-08 21:16

from django.db import migrations


def equalize_pools(apps, schema_editor):
    """One-time: flatten every stage's ganyan pools to the uniform scheme.

    Existing stages were seeded with escalating pools (GROUP 100 → FINAL 300).
    This sets every stage to 100/100/100 regulation + 50/50/50 penalty. From
    here on pools are admin-owned: seed_wc2026 writes them only via
    create_defaults, and no later migration re-touches them, so admin edits
    persist across deploys.
    """
    Stage = apps.get_model("tournament", "Stage")
    Stage.objects.all().update(
        pool_exact=100,
        pool_diff=100,
        pool_result=100,
        pool_penalty_winner=50,
        pool_penalty_score=50,
        pool_penalty_diff=50,
    )


def noop_reverse(apps, schema_editor):
    # Irreversible by design — the pre-equalization values aren't recoverable.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_stage_pool_penalty_pass_and_more'),
    ]

    operations = [
        migrations.RunPython(equalize_pools, noop_reverse),
    ]
