# Generated by Django 5.1.4 on 2026-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_equalize_ganyan_pools'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualresult',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual entry'), ('API', 'football-data.org live sync')], default='MANUAL', max_length=10),
        ),
    ]
