# Generated by Django 5.1.4 on 2026-06-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_actualresult_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualresult',
            name='away_score_aet',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actualresult',
            name='home_score_aet',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
