# Generated by Django 5.1.4 on 2026-06-30 20:36

from django.db import migrations, models

# Penalty pools were equalized to 50 in 0009; lowering the default to 25 — a
# smaller bonus than the regulation criteria (which stay at 100).
_OLD, _NEW = 50, 25


def _retune(apps, schema_editor, frm, to):
    """Move every stage still on the old default to the new one. Only touches
    rows still at `frm`, so a value an admin deliberately set to something else
    is preserved (pools are admin-owned after creation; see seed_wc2026)."""
    Stage = apps.get_model("tournament", "Stage")
    for f in ("pool_penalty_winner", "pool_penalty_score", "pool_penalty_diff"):
        Stage.objects.filter(**{f: frm}).update(**{f: to})


def lower_penalty_pools(apps, schema_editor):
    _retune(apps, schema_editor, _OLD, _NEW)


def restore_penalty_pools(apps, schema_editor):
    _retune(apps, schema_editor, _NEW, _OLD)


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_actualresult_away_score_aet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='pool_penalty_diff',
            field=models.PositiveIntegerField(default=25, help_text='Ganyan pool: predicted the penalty shootout goal difference (signed home−away). Draw predictions only. Knockout only.'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='pool_penalty_score',
            field=models.PositiveIntegerField(default=25, help_text='Ganyan pool: predicted the exact penalty shootout score. Only draw predictions carry a shootout score, so this is open to them only. Knockout only.'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='pool_penalty_winner',
            field=models.PositiveIntegerField(default=25, help_text='Ganyan pool: correctly named the team that advanced via penalties. Open to any prediction (implied winner from a non-draw, chosen penalty winner from a draw). Knockout only.'),
        ),
        migrations.RunPython(lower_penalty_pools, restore_penalty_pools),
    ]
