# Generated by Django 5.1.4 on 2026-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_alter_stage_pool_penalty_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='pool_advancer',
            field=models.PositiveIntegerField(default=25, help_text="Ganyan pool: named the advancing team ('turlayan') on a match that went to penalties — implied winner for decisive predictions, chosen shootout winner for draw predictions. Open to everyone on the fixture. Knockout only."),
        ),
    ]
