# Generated by Django 5.1.4 on 2026-06-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient address, kept even if the user is later deleted.', max_length=254)),
                ('kind', models.CharField(choices=[('daily_morning', 'Daily — sabah'), ('daily_evening', 'Daily — akşam'), ('invite_welcome', 'Davet — hoş geldin'), ('onboarding', 'Onboarding'), ('magic_link_signup', 'Magic link — kayıt'), ('magic_link_login', 'Magic link — giriş')], max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Gönderildi'), ('dropped', 'Düştü (dummy backend)'), ('rejected', 'Reddedildi'), ('failed', 'Hata')], max_length=16)),
                ('slate_date', models.DateField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['kind', 'slate_date'], name='notificatio_kind_fd47e9_idx'), models.Index(fields=['-created_at'], name='notificatio_created_4c6dec_idx')],
            },
        ),
    ]
