# Generated by Django 5.1.4 on 2026-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Gönderildi'), ('dropped', 'Düştü (dummy backend)'), ('rejected', 'Reddedildi'), ('failed', 'Hata'), ('bounced', 'Geri döndü (bounce)'), ('complained', 'Şikayet (spam)')], max_length=16),
        ),
    ]
