# Generated by Django 5.1.4 on 2026-07-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_emaillog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('daily_morning', 'Daily — sabah'), ('daily_evening', 'Daily — akşam'), ('invite_welcome', 'Davet — hoş geldin'), ('onboarding', 'Onboarding'), ('magic_link_signup', 'Magic link — kayıt'), ('magic_link_login', 'Magic link — giriş'), ('round_reminder', 'Tur — tahmin hatırlatma')], max_length=32),
        ),
    ]
